# Base packages installed on all machines
# These packages form the foundation of your system

description: Base packages for all machines

packages:
  - base
  - base-devel
  - clang # why you not included?!?!?!??!?!?!??!?!??!?!?!??!
  - linux
  - linux-firmware
  - networkmanager
  - neovim # Hyperextensible Vim-based text editor
  - fresh-editor-bin # TUI Code Editor
  - python-pynvim # Python support for Neovim
  - vim # to quit vim, pay attention to `:` colon also to enter Command mode. `:q` just quit, `:q!` force quit, `:wq` save and quit
  - git
  - go-yq # YAML processor for dcli
  - pipewire
  - htop
  - btop
  - tmux
  - man-db
  - man-pages
  - fastfetch
  - fet.sh-git
  - neofetch
  - alacritty
  #- timeshift # disk snapshot
  - ttf-jetbrains-mono-nerd
  - octopi # Synaptics but for Arch btw
